package org.be.kuleuven.hci.stepup.util;

public class StepUpConstants {

	public static final String URLPUSHEVENT = "http://ariadne.cs.kuleuven.be/wespot-dev-ws/rest/pushEvent";
	public static final String IMGPATH = "/img/badges/";
	public static final String DIIGOVERB = "bookmarked";
	public static final String BLOGPOST= "posted";
	public static final String BLOGCOMMENT = "commented";
	public static final String TWITTER = "tweeted";
	public static final String RETWEET = "retweeted";
	//WeSPOT requirement
		public static final String PHASE1 = "1";
		public static final String PHASE1_S1 = "Reflection";
		public static final String PHASE1_S2 = "Ethics";
		public static final String PHASE1_S3 = "Empirical meaning";
		public static final String PHASE1_S4 = "Embedding";
		public static final String PHASE1_S5 = "Existing knowledge";
		public static final String PHASE1_S6 = "Mental representation";
		public static final String PHASE1_S7 = "Language definitions";
		public static final String PHASE1_S8 = "Field of research";
		public static final String PHASE1_S9 = "Content";
		public static final String PHASE2 = "2";
		public static final String PHASE2_S1 = "Reflection";
		public static final String PHASE2_S2 = "Indicators";
		public static final String PHASE2_S3 = "Predictions";
		public static final String PHASE2_S4 = "Context";
		public static final String PHASE2_S5 = "Resources";
		public static final String PHASE2_S6 = "Methodology";
		public static final String PHASE2_S7 = "Ethics";	
		public static final String PHASE3 = "3";
		public static final String PHASE3_S1 = "Reflection";
		public static final String PHASE3_S2 = "ARLearn";
		public static final String PHASE3_S3 = "Context";
		public static final String PHASE3_S4 = "Systematic observation";
		public static final String PHASE3_S5 = "Experimentation";
		public static final String PHASE3_S6 = "Tools";
		public static final String PHASE3_S7 = "Simulation";
		public static final String PHASE3_S8 = "Data storage";
		public static final String PHASE3_S9 = "Data security";
		public static final String PHASE3_S10 = "Documentation";	
		public static final String PHASE4 = "4";
		public static final String PHASE4_S1 = "Reflection";
		public static final String PHASE4_S2 = "Quantitative analysis";
		public static final String PHASE4_S3 = "Qualitative analysis";
		public static final String PHASE4_S4 = "Tools";
		public static final String PHASE4_S5 = "Visualisation";
		public static final String PHASE4_S6 = "Noise reduction";
		public static final String PHASE5 = "5";
		public static final String PHASE5_S1 = "Reflection";
		public static final String PHASE5_S2 = "Embedding";
		public static final String PHASE5_S3 = "Confirmation";
		public static final String PHASE5_S4 = "Exhaustion";
		public static final String PHASE5_S5 = "Threshold";
		public static final String PHASE5_S6 = "Relevance";
		public static final String PHASE5_S7 = "Significance";
		public static final String PHASE6 = "6";
		public static final String PHASE6_S1 = "Reflection";
		public static final String PHASE6_S2 = "Writing up";
		public static final String PHASE6_S3 = "Strategy";
		public static final String PHASE6_S4 = "Audience";
		public static final String PHASE6_S5 = "Tools";
		public static final String PHASE6_S6 = "Dissemination";
		public static final String PHASE6_S7 = "Discussion";
		public static final String PHASE6_S8 = "Feedback";
}
